//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace master.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProducts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartnerProducts()
        {
            this.Partners = new HashSet<Partners>();
        }
    
        public int Id { get; set; }
        public int NameProduct { get; set; }
        public int NamePartner { get; set; }
        public int kolvoProduct { get; set; }
        public System.DateTime SaleDate { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual Products Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partners> Partners { get; set; }
    }
}
