//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace master.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        public int Id { get; set; }
        public int NameTypePartners { get; set; }
        public int NamePartner { get; set; }
        public string SurName { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string Email { get; set; }
        public string Number { get; set; }
        public int IndexA { get; set; }
        public string Obl { get; set; }
        public string City { get; set; }
        public int House { get; set; }
        public decimal INN { get; set; }
        public int Reit { get; set; }
    
        public virtual PartnerProducts PartnerProducts { get; set; }
        public virtual TypePartners TypePartners { get; set; }
    }
}
