//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace master.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductType
    {
        public int Id { get; set; }
        public int NameProduct { get; set; }
        public decimal KType { get; set; }
    
        public virtual Product1 Product1 { get; set; }
    }
}
